-- ── Found By Scout — Feature GLB flag (SUPERSEDED, see below) ──────────────
-- This column is no longer read by anything. It gated an experiment that put
-- the feature GLB in the hero alongside the main scan, which turned out to be
-- the wrong place for it: feature.glb is exported in place from the scan's own
-- coordinate space, and the scan already contains the feature, so the hero
-- rendered two copies of the same object in the same spot, one spinning.
--
-- The feature now appears only where it was always going to read properly — a
-- gallery slot of type 'glb', which gives it an isolated canvas, its own
-- auto-fitting camera and a background. That is configured per slot in
-- gallery_rows, so it needs no column and no flag.
--
-- The hero shows model-high.glb or model-low.glb. Nothing else.
--
-- The column is left in place rather than dropped, for the same reason `scout`
-- was in 004: Supabase flags DROP COLUMN as destructive and nothing reads this
-- one, so leaving it costs nothing. The admin no longer sends it.
--
-- To drop it later:
--   alter table parks drop column if exists has_feature_glb;
alter table parks add column if not exists has_feature_glb boolean not null default false;

-- ── The dead `use_contour_model` column — deliberately NOT dropped ─────────
-- Added in 001 to route the hero to ContourModel, a second viewer for
-- terrain/contour data. That component was deleted; the column and its admin
-- checkbox outlived it, so for some time the form offered a toggle that
-- changed nothing. The checkbox is now gone from the admin.
--
-- The column stays, for the same reason `scout` did in 004: Supabase flags any
-- DROP COLUMN as destructive, and nothing reads or writes this one any more,
-- so leaving it costs nothing. Note the admin no longer sends it, so existing
-- values simply freeze where they are.
--
-- To drop it later:
--   alter table parks drop column if exists use_contour_model;

-- Verify:
--   select slug from parks order by slug;
